import Link from "next/link";

export const metadata = { title: "Privacy Policy — ContractGate" };

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0a0d12] flex flex-col items-center justify-center px-4 py-24">
      <div className="max-w-2xl w-full">
        <h1 className="text-2xl font-bold text-slate-100 mb-2">Privacy Policy</h1>
        <p className="text-slate-500 text-sm mb-10">Last updated: May 2026</p>

        <div className="space-y-6 text-sm text-slate-400 leading-relaxed">
          <p>
            ContractGate (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;) is committed to protecting
            your personal information. This policy describes what we collect, how we
            use it, and your rights.
          </p>

          <section>
            <h2 className="text-slate-200 font-semibold mb-2">1. Information We Collect</h2>
            <p>
              We collect information you provide directly (such as your name and email
              address when you create an account), usage data generated by your
              interaction with the Service, and technical data such as IP address and
              browser type.
            </p>
          </section>

          <section>
            <h2 className="text-slate-200 font-semibold mb-2">2. How We Use Your Information</h2>
            <p>
              We use the information we collect to provide and improve the Service,
              send transactional communications, respond to support requests, and
              comply with legal obligations. We do not sell your personal data to
              third parties.
            </p>
          </section>

          <section>
            <h2 className="text-slate-200 font-semibold mb-2">3. Data Retention</h2>
            <p>
              We retain your account data for as long as your account is active or as
              needed to provide the Service. Audit log retention periods are governed
              by your plan tier. You may request deletion of your data at any time by
              contacting us.
            </p>
          </section>

          <section>
            <h2 className="text-slate-200 font-semibold mb-2">4. Security</h2>
            <p>
              We implement industry-standard security measures to protect your data,
              including encryption in transit (TLS) and at rest. No method of
              transmission over the internet is 100% secure, and we cannot guarantee
              absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-slate-200 font-semibold mb-2">5. Your Rights</h2>
            <p>
              Depending on your jurisdiction, you may have rights to access, correct,
              or delete your personal data, or to object to certain processing. To
              exercise these rights, contact us at the address below.
            </p>
          </section>

          <section>
            <h2 className="text-slate-200 font-semibold mb-2">6. Contact</h2>
            <p>
              Privacy questions or requests? Email us at{" "}
              <a
                href="mailto:sales@contractgate.io"
                className="text-green-400 hover:text-green-300"
              >
                sales@contractgate.io
              </a>
              .
            </p>
          </section>
        </div>

        <div className="mt-12 pt-6 border-t border-[#1f2937]">
          <Link href="/" className="text-sm text-slate-500 hover:text-slate-400 transition-colors">
            ← Back to ContractGate
          </Link>
        </div>
      </div>
    </div>
  );
}
